import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

import { cn } from "@/lib/utils";

import { Toaster } from "@/components/ui/toaster";

import SideNavbar from "@/components/SideNavbar";

import { ClerkProvider, ClerkLoaded, ClerkLoading } from "@clerk/nextjs";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider
      publishableKey={process.env.NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY}
    >
      <html lang="en">
        <body
          className={cn(inter.className, ` text-black overflow-y-scroll`, {
            "debug-screens": process.env.NODE_ENV === "development",
          })}
        >
          <ClerkLoading>
            <div>Clerk is loading...</div>
          </ClerkLoading>

          <ClerkLoaded>
            <div className="flex gap-5">
              <SideNavbar />
              <main className="p-8 w-full">{children}</main>
              <Toaster />
            </div>
          </ClerkLoaded>
        </body>
      </html>
    </ClerkProvider>
  );
}
