const REDIS_USER_SORTED_SET_KEY = "users:sorted";
const REDIS_USER_STREAM_KEY = "users:stream";
const REDIS_USER_WITHSCORES = "WITHSCORES";

export { REDIS_USER_SORTED_SET_KEY, REDIS_USER_STREAM_KEY, REDIS_USER_WITHSCORES };